### ISSUE TITLE
activation failed

### ISSUE THREAD

**Issue by git-tracker** [massgravel/massgrave.dev#11]
error code: 0x800705b4
maybe win update is not working?
<img width="380" alt="err" src="https://github.com/massgravel/massgrave.dev/assets/125434011/32f48de7-a775-4a4f-b8eb-9f744de92787">

**Comment by WindowsAddict** [comment]
open command prompt as admin and enter
```
reg delete HKU\S-1-5-19\Software\Microsoft\IdentityCRL /f
slmgr /ato
```
