### ISSUE TITLE
Activation

### ISSUE THREAD

**Issue by Kalki66** [massgravel/massgrave.dev#14]
Cant activate Windows 11 LTSC IOT shows 

![image](https://github.com/user-attachments/assets/fc933979-cbb1-4b1e-afec-ab14b6f72fb8)

**Comment by WindowsAddict** [comment]
Solution is explained in the picture. 
https://massgrave.dev/windows_ltsc_links
Download and install full version of LTSC from here

**Comment by Kalki66** [comment]
Thanks
