### ISSUE TITLE
The webpage doesn't load

### ISSUE THREAD

**Issue by ChaseKnowlden** [massgravel/massgrave.dev#20]
![image](https://github.com/user-attachments/assets/61a05f12-c5bd-4a82-b9ae-88d378494db3)

**Comment by WindowsAddict** [comment]
Update your browser.

**Comment by ChaseKnowlden** [comment]
The Chrome Version is 22.0.1229.95

**Comment by ave9858** [comment]
why?

**Comment by ChaseKnowlden** [comment]
![image](https://github.com/user-attachments/assets/309b0a4c-f1a3-4025-86f2-81d648868068)

The Chrome version is 131.0.6778.140 (the latest version of chrome)

**Comment by ave9858** [comment]
Great, glad the issue is solved
