### ISSUE TITLE
buzzheavier direct download button doesn't work

### ISSUE THREAD

**Issue by Apig-Sharbo** [massgravel/massgrave.dev#21]
Hello,

I'm trying to download "Windows 10 IoT Enterprise LTSC ❤️", and following [https://massgrave.dev/windows_ltsc_links](https://massgrave.dev/windows_ltsc_links), i see that yes, the link forwards to buzzheavier page, but **Direct: Download** doesn't work for me. I've tried from different devices.

**Comment by WindowsAddict** [comment]
@Apig-Sharbo 
whats the issue in downloading from buzzheavier?

**Comment by WindowsAddict** [comment]
share screenshot/video of the error.

**Comment by Apig-Sharbo** [comment]
https://we.tl/t-s7KaB7gAj2

**Comment by WindowsAddict** [comment]
It's working fine here, as per the stats shown on the page, it's working for many people. 
Try a different browser, try Cloudflare VPN, and see if it helps.

**Comment by Apig-Sharbo** [comment]
Thanks, will try some thing.

**Comment by Apig-Sharbo** [comment]
It's working now.

The problem was Adguard blocking it.
Exiting the app fixed it.

Thanks!

**Comment by ave9858** [comment]
update your filter lists and try with adguard again
