### ISSUE TITLE
Webpage looks broken

### ISSUE THREAD

**Issue by ChaseKnowlden** [massgravel/massgrave.dev#22]
![image](https://github.com/user-attachments/assets/66a9c33a-97a2-491d-a85e-1c79746a8648)

The webpage looks wrong and crashes the page.

User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.59 Safari/537.36

**Comment by ave9858** [comment]
update your browser

**Comment by ChaseKnowlden** [comment]
![image](https://github.com/user-attachments/assets/6919d1f1-9337-47ba-b02c-ab0fe2069eee)

Fixed.
